# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Login Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for Login Example

  pod 'DropDown'
  pod 'SWRevealViewController', '~> 2.3'
  
end

target 'Login ExampleTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'Login ExampleUITests' do
  # Pods for testing
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
            end
        end
    end
end
